version: "3.9"

services:
  ### Front
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front.nsmobile.be
    image: front.nsmobile.be
    restart: unless-stopped
    networks:
      - edge
    labels:
      caddy: nsmobile.be, www.nsmobile.be
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  edge:
    external: true
